### ISSUE TITLE
Umbrella issue on improvements for contributing to the docs

### ISSUE THREAD

**Issue by jonasrosland** [goharbor/website#140]
There are a few things that can be done to help with contributing to the website and docs:

- [ ] Create issue template for the repo explaining the process
- [ ] Create an "Edit" button on the right hand side of the docs
- [ ] Make sure issues are created in the website repo instead of the harbor repo

**Comment by a-mccarthy** [comment]
closing this in favor of the changes in this issue: https://github.com/goharbor/harbor/issues/14590
